[package]
name = "test_rustc"
version = "0.1.0"
authors = ["ClownZong <2829294028@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
